# Generated by Django 4.1.1 on 2022-10-06 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbortrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=240)),
                ('location', models.CharField(max_length=255)),
                ('relasedate', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbortrary', to='appex.user')),
            ],
        ),
    ]
